version: '3.8'

services:
  postgres-db:
    image: postgres:16
    environment:
      POSTGRES_USER: coneyuser 
      POSTGRES_PASSWORD: coneypassword
      POSTGRES_DB: coneydb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U coneyuser -d coneydb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
 
  web:
    build:
      context: .
      dockerfile: .docker/cs.dev.dockerfile
    ports:
      - "5293:5293"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=postgres-db;Database=coneydb;Username=coneyuser;Password=coneypassword"
      ASPNETCORE_PORT: 5293
    depends_on:
      postgres-db:
        condition: service_healthy       
    volumes:
      - .:/app  
      - ~/.nuget/packages:/root/.nuget/packages

volumes:
  postgres-data:
