# IMPORTANT: No environment variables are saved because this file is for development and testing only.
version: '3.8'

services:
  postgres-db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER} 
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U coneyuser -d coneydb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
 
  web:
    build:
      context: .
      dockerfile: .docker/cs.dev.dockerfile
    ports:
      - ${APP_EXEC_PORT}:${APP_EXEC_PORT}
    environment:
      ASPNETCORE_ENVIRONMENT: ${ENVIRONMENT}
    depends_on:
      postgres-db:
        condition: service_healthy       
    volumes:
      - .:/app  
      - ~/.nuget/packages:/root/.nuget/packages

volumes:
  postgres-data:
